[package]
name = "better-comprehension"
version = "1.0.0"
edition = "2024"


[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.100", features = ["full", "extra-traits"] }
quote = "1.0.40"
proc-macro2 = "1.0.94"
